### ISSUE TITLE
Invalid examples in readme

### ISSUE THREAD

**Issue by gabbhack** [ire4ever1190/ponairi#13]
SQL queries must be with `sql` prefix, but they are not. Example:
https://github.com/ire4ever1190/ponairi/blob/91304287482064d4c71edbaeadd5d6fe0baa5e92/readme.md?plain=1#L57-L61

Valid example in docs - https://tempdocs.netlify.app/ponairi/stable/ponairi.html#getting-started-read

**Comment by ire4ever1190** [comment]
Thanks for pointing that out, will fix asap :+1:
