### ISSUE TITLE
add support for index

### ISSUE THREAD

**Issue by hamidb80** [ire4ever1190/ponairi#15]
Hey, I think it's useful to add `index` pragma.

```nim
type
  Model = object
    ...
    title {.index.}: string

```

**Comment by ire4ever1190** [comment]
Yup sounds useful 👌 should hopefully be able to implement it quickly

**Comment by hamidb80** [comment]
Thanks for adding this feature. that was so quick!

Please bump the version in `.nimble` file so I don't have to write:
```
nimble install ponairi@#head
```

**Comment by ire4ever1190** [comment]
Sorry about that, forgot to push the new tag

Done now :+1:
